
symbols_complex:list[str] = [
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
    'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
    'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', ' ', '1', '2', '3', '4', '5', '6',
    '7','8','9','0','.', '!', '?', '€', '$', '%', '+', '-', '#', ',', ';', '_', ':', '<', '>', '|', '/',
    '~', '=', '&', '(', ')', '{', '}', '@', 'ä', 'ö', 'ü', 'Ä', 'Ö', 'Ü', 'ß', '"', "'", '*', '^',
    '[', ']', '`', '§', '°', '™', '®', '©'
    ]

symbols_simple:list[str] = [
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
    'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
    'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', ' ', '1', '2', '3', '4', '5', '6',
    '7','8','9','0'
    ]

testing_keys:list[str] = [
    'AAAA',
    'Test',
    'TestKey',
    'Password',
    'Hello World',
    'HelloWorld!',
    'ComplexKey123',
    'ABCD',
    'ABCDEFG',
    'Password12345',
    'Spaces     Spaces',
    '---',
    '123',
    '54321',
    '€=$',
    'Mein Test Passwort',
    'Alexander E******',
    'Alex',
    'Türgriff',
    'Super tolles passwort',
    'SecretKey',
    'Hidden',
    'Find Message',

    'Meistgenutzte Passwörter in Deutschland:',
    '123456',
    'passwort',
    '12345',
    'hallo',
    'schatz',
    'basteln',
    'berlin',
    '11111',
    'qwertz',
    'abc123',
    'iloveyou',
    'passwort1',
    'monkey',
    'keineahnung',

]

testing_messages:list[str] = [
    'Hello World!',
    'Hallo Welt',
    'Meine Nachricht',
    'Hey, wie geht es dir heute?',
    'Diese Nachricht wurde verschlüsselt',
    'Das ist ein Test.',
    'Passwort: xb75hJBBBEgh',
    'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
    'abcdefghijklmnopqrstuvwxyz',
    '1234567890',
    'süßes Passwort',
    '$$$ < €€€ < %',
    'Decoded Message',
    'How are you doing today?',
    'Hier ist alles super!',
    'Das ist ein normaler Text, welcher auch S0nderzeichen enthält! Oder?',
    'Geheime Daten: x: 5, b: 574, c: 1234',
    'Überzeugendes Programm!',
    'Alexander E******* is AcoAlex',
    'Wir brauchen mehr lange Nachrichten für die längeren Testschlüssel.',
    'Message = Nachricht, Key = Schlüssel',
    'Hallo Dieter, du kannst diese Nachricht nur mit dem Key 1243 lesen.',
    'Passwort geknackt!',
    'This WAS a secret message.',
    'Emoji Time: ;( :D :p :/ :O ;)',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.',
    'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.',
    'Ab hier weitere lange Beispielpasswörter, welche man verschlüsseln kann:',
    'Employee ID: 47208470; Name: Max Mustermann; Department: IT; Holiday Request: Approved',
    'Mitarbeiter-ID: 792947; Name: Mustermann, Max; Abteilung: IT; Urlaubsantrag: Genehmigt',
    'Paycheck Information: Amount: €1500, Date: 15th of the month, Status: Paid',
    'E-Mail Logs: Sender: Alex, Recipient: Ben, Subject: Meeting Reminder, Date: 2025-08-11',
    'Computer Log: User: admin, IP: 192.168.0.254, Status: Success, Timestamp: 2025-08-11 15:13:00',
    'Login Attempt: The user acoalex tried to log in your account at 2027-08-11 16:14:50 from Russia.',
    'Formatted Logs: 76913874613746013748980978425078245874285457829578802745078094285792845978',
    "Here's my new number: +49 176 45678901 #NOT A REAL NUMBER",
    'Please retype your Linked-In password...',
    'I hope reversed engineering is not needed for this message.',
    'UPPERCASE LETTERS ARE UNDERPRESENTED SO I AM USING THEM HERE TO INCREASE THEIR FREQUENCY!',
    'The human ear can hear between 20 Hz and 20 kHz, but most people lose some hearing as they age.',
    'ChatGPT-5 was not able to break this encryption',
    'Sony user information: E-Mail: sonylover@gmail.com, Password: dragon47!, credit card: 1234-5678-9012-3456',
    'Hi random github user, I hope you like this encryption script.',
    '!!! please do not use this script for illegal activities !!!',
    'Webstore Log: User: max_mustermann5, Action: Purchase, Item: Laptop, Price: $1200, Date: 2025-09-12 Status: Waiting for shipping',
    'Deutscher Log: Benutzer: ben_mustermann6, Aktion: Kauf, Artikel: Smartphone, Preis: 1350€, Datum: 15.03.2022 Status: Wartet auf Versand',
    'Package Tracking: Tracking Number: 83946829, Carrier: DHL, Status: In Transit, Estimated Delivery: 2025-09-20',
    'Ich würde mal behaupten, dass reicht :D',
]

most_used_letters_english:list[str] = [
    'e', 'n', 'i', 't', 'a', 'r', 's',
    'h', 'o', 'd', 'l', 'u', 'c', 'g',
    'm', 'w', 'f', 'b', 'p', 'k', 'y',
    'v', 'z', 'x', 'q', 'j', 'ü', 'ä',
    'ö', '1', '2', '3', '4', '5', '6',
    '7', '8', '9', '0', 'E', 'N', 'I',
    'T', 'A', 'R', 'S', 'H', 'O', 'D',
    'L', 'U', 'C', 'G', 'M', 'W', 'F',
    'B', 'P', 'K', 'Y', 'V', 'Z', 'J',
    'X', 'Q', 'Ü', 'Ä', 'Ö', ' ', 'ß',
    '.', ',', '!', '?', '€', '$', '%',
    '+', '-', '#', ';', '_', ':', '<',
    '>', '|', '/', '~', '=', '&', '(',
    ')', '{', '}', '@', '"', "'", '*',
    '^', '[', ']', '`', '§', '°', '©',
    '®', '™'
]

